<a href="https://colab.research.google.com/github/Karthi-gitt/Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
#create series
s = pd.Series([1,2,3,4,5,6,7])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [3]:
# Descriptive statistics
print(s.describe())

count    7.000000
mean     4.000000
std      2.160247
min      1.000000
25%      2.500000
50%      4.000000
75%      5.500000
max      7.000000
dtype: float64

In [4]:
print(s.mean())
print(s.std())
print(s.min())
print(s.max())

4.0
2.160246899469287
1
7

In [5]:
mapping = s.map(lambda x :x*2)
print(mapping)
print(s)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [7]:
applies = s.apply(lambda x : x ** 2)
print(applies)
print(s)

0     1
1     4
2     9
3    16
4    25
5    36
6    49
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [8]:
s1 = pd.Series([4,7,54,23,92,41])
sorted = s1.sort_values()
print(sorted)

0     4
1     7
3    23
5    41
2    54
4    92
dtype: int64

In [9]:
dropped = s.drop(1)
print(dropped)
print(s)

0    1
2    3
3    4
4    5
5    6
6    7
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [10]:
#Handling Missing data
s2 = pd.Series([2,4,6,np.nan,7,0])
print(s2.isnull())

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [11]:
#opposite of isnull()
print(s2.notnull())

0     True
1     True
2     True
3    False
4     True
5     True
dtype: bool

In [12]:
#Filling missing values
print(s2.fillna(0))

0    2.0
1    4.0
2    6.0
3    0.0
4    7.0
5    0.0
dtype: float64

In [13]:
s3 = pd.Series([4,7,3,None,8,2,np.nan])
print(s3)
print(s3.dropna())

0    4.0
1    7.0
2    3.0
3    NaN
4    8.0
5    2.0
6    NaN
dtype: float64
0    4.0
1    7.0
2    3.0
4    8.0
5    2.0
dtype: float64

In [14]:
print(s.iloc[2])  #1,2,3,4,5,6,7
print(s.iloc[-2])  #6

3
6

In [15]:
greater_num = s[s<=5]
print(greater_num)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
print(s.sum())

28

In [17]:
print(s.aggregate(['sum','std','mean']))

sum     28.000000
std      2.160247
mean     4.000000
dtype: float64

In [18]:
data = {
    "name" : ['sruthi','hema','ashok','rohith','venkatesh','mohith','Azmath',
              'Ravi','priya','Nikhitha','shila','bhoomika','sushma'],
    "age" : [23,32,21,15,65,51,22,43,25,89,99,20,19],
    "branch" : ['CSE','ECE','AIML','CSM','DS','IOT','CS','Mech','Civil','EEE','IT',
                'AIDS','FD'],
    "Address" : ['Hyd','panjab','Assam','Bihar','JK','chennai','Bglr','kerala','pune',
                 'Mumbai','Goa','Pondi','Coimb']
}
df = pd.DataFrame(data)
df

         name  age branch  Address
0      sruthi   23    CSE      Hyd
1        hema   32    ECE   panjab
2       ashok   21   AIML    Assam
3      rohith   15    CSM    Bihar
4   venkatesh   65     DS       JK
5      mohith   51    IOT  chennai
6      Azmath   22     CS     Bglr
7        Ravi   43   Mech   kerala
8       priya   25  Civil     pune
9    Nikhitha   89    EEE   Mumbai
10      shila   99     IT      Goa
11   bhoomika   20   AIDS    Pondi
12     sushma   19     FD    Coimb

In [19]:
df.head(5)

        name  age branch Address
0     sruthi   23    CSE     Hyd
1       hema   32    ECE  panjab
2      ashok   21   AIML   Assam
3     rohith   15    CSM   Bihar
4  venkatesh   65     DS      JK

In [20]:
df.tail(5)

        name  age branch Address
8      priya   25  Civil    pune
9   Nikhitha   89    EEE  Mumbai
10     shila   99     IT     Goa
11  bhoomika   20   AIDS   Pondi
12    sushma   19     FD   Coimb

In [21]:
data1 = {
    "name" : ['sruthi','hema','ashok','rohith','venkatesh','mohith','Azmath',
              'Ravi','priya','Nikhitha','shila','bhoomika','sushma'],
    "age" : [23,32,21,15,65,51,22,43,25,89,99,20,19]}
df1 = pd.DataFrame(data1)

data2 = {
    "name" : ['sruthi','hema','ashok','rohith','venkatesh','mohith','Azmath',
              'Ravi','priya','Nikhitha','shila','bhoomika','sushma'],
    "branch" : ['CSE','ECE','AIML','CSM','DS','IOT','CS','Mech','Civil','EEE','IT',
                'AIDS','FD']
}
df2 = pd.DataFrame(data2)
merged = pd.merge(df1,df2,on="name")
merged

         name  age branch
0      sruthi   23    CSE
1        hema   32    ECE
2       ashok   21   AIML
3      rohith   15    CSM
4   venkatesh   65     DS
5      mohith   51    IOT
6      Azmath   22     CS
7        Ravi   43   Mech
8       priya   25  Civil
9    Nikhitha   89    EEE
10      shila   99     IT
11   bhoomika   20   AIDS
12     sushma   19     FD